# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Movies CI/CD Pipeline 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'
    - name: Installing
      run: npm install
    - name: Running Unit Tests
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo "vlzahariev"
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Render.com
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          api-Key: ${{ secrets.MY_RENDER_API_KEY }}
          service-id: ${{ secrets.SERVICE_ID }}
  
  ui_tests:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'npm'
      - name: Installing NPM
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Running UI Tests
        run: npm run test:ui
